### ISSUE TITLE
[Balance] Moving rotation

### ISSUE THREAD

**Issue by solitha** [SimCMinMax/AethysRotation#100]
Starsurge/Starfall could be in the GCD during movement. I seem to recall they were, but haven't seen them there in a while.

**Comment by Kutikuti** [comment]
Yeah forgot to add them back after the big apl update. they are only shown when you have a proc from wrists. I'll add them when i have some time

**Comment by Kutikuti** [comment]
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/c553508e7e983d0ab75c3aee2792a9c533456ae8
