### ISSUE TITLE
[Elemental Shaman] Totems suggested too much

### ISSUE THREAD

**Issue by solitha** [SimCMinMax/AethysRotation#101]
Since I'm actually playing this toon I've been having this happen quite a lot. Talents and gear here https://worldofwarcraft.com/en-us/character/silvermoon/turquoa

I'll post a screenie in Discord so you can see everything I had going on at the moment. Maybe there's a clue in there somewhere.

**Comment by lithium720** [comment]
Aethys was pushing a release (with a fix I made awhile ago to solve this problem you're describing) at the same time you made this issue. Could you give it a try again with the new release and let me know if it's still a problem?

**Comment by solitha** [comment]
It may be a while before I run that toon through challenging content again, so if you want to want to close this out and assume it was fixed in that pass feel free. Not like I can't start a new ticket later if needed :)

**Comment by lithium720** [comment]
I played Ele through a bunch of world quests and the world bosses for the week and never encountered this issue yesterday. Are you _sure_ you were updated when you tested it again? I can't seem to get it to happen on my end. :S

**Comment by solitha** [comment]
Seems to be fixed. It did hang once, but I bulled through that one moment and it continued normally. Thanks lithium!
