### ISSUE TITLE
 [Demonology Warlock] Doom

### ISSUE THREAD

**Issue by taintedbunny** [SimCMinMax/AethysRotation#103]
Hey Guys,

The add-on is suggesting to refresh Doom long before it wears off.
Don't we want Doom to wear off so we get the damage from it then reapply it?

**Comment by ghr74** [comment]
Doom is a DoT dealing damage every X seconds and as such can be refreshed with pandemic. For more in-depth info, maybe refer to [this writeup](http://lockonestopshop.com/#!/Demonology/Spec%20Mechanics).
