### ISSUE TITLE
Lua error with affliction warlock

### ISSUE THREAD

**Issue by shaq3232** [SimCMinMax/AethysRotation#105]
I keep getting this lua error

Message: ...terface\AddOns\AethysRotation_Warlock\Affliction.lua:221: attempt to index field 'Fear' (a nil value)
Time: 01/08/18 14:22:15
Count: 457
Stack: ...terface\AddOns\AethysRotation_Warlock\Affliction.lua:221: attempt to index field 'Fear' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function `origErrorHandler'
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
...terface\AddOns\AethysRotation_Warlock\Affliction.lua:221: in function <...terface\AddOns\AethysRotation_Warlock\Affliction.lua:206>
...terface\AddOns\AethysRotation_Warlock\Affliction.lua:1080: in function `?'
Interface\AddOns\AethysRotation\Main.lua:431: in function <Interface\AddOns\AethysRotation\Main.lua:409>

Locals: errorMessage = "...terface\AddOns\AethysRotation_Warlock\Affliction.lua:221: attempt to index field 'Fear' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

**Comment by Kutikuti** [comment]
Fixed with https://github.com/SimCMinMax/AethysRotation/commit/66d6344f7098b1ab0b1728fba5f28231f8ba4fab
