### ISSUE TITLE
[WW Monk] Stuck on c/ds

### ISSUE THREAD

**Issue by solitha** [SimCMinMax/AethysRotation#106]
Was just fighting LFR Sassz'ine. At one point I got stuck on Whirling Dragon Punch, then Energizing Elixir, while both were on cooldown.
Toon with talents and legendaries (or lack thereof): https://worldofwarcraft.com/en-us/character/silvermoon/fyrfox

**Comment by Hinalover** [comment]
Are you using the current Alpha build? If not try using that first. I cleaned up the code so that it should be working fairly well.

**Comment by solitha** [comment]
WELL OF COURSE I AM... not. Forgot to update today. I am quite pleased with how well it's working. Version I am using ga6b3f8a-alpha. That instance only happened once in the several LFRs I've run today.

**Comment by Hinalover** [comment]
Yea that release was 1 day before I made a lot of changes so try it out now.

**Comment by solitha** [comment]
Only happened the once, wasn't current build, gonna assume fixed until proven guilty.
