### ISSUE TITLE
[MM Hunter] Arcane shot issue

### ISSUE THREAD

**Issue by lexic93** [SimCMinMax/AethysRotation#110]
Dunno if thats broken or something but why the addon shows "use arcane shot" when you are over 100+ focus.. even 130 and that leaves when you hit the proc for marked shot window

**Comment by az1986** [comment]
any update on this fix? experience this same bug constantly.

**Comment by Defmaster** [comment]
Try change line 473:
```
if IsCastableP(S.AimedShot) and PlayerFocusPredicted() + Player:FocusCastRegen(S.AimedShot:ExecuteTime()) > Player:FocusMax() and not Player:Buff(S.SentinelsSight) then
```

and 357:
```
    if IsCastableP(S.AimedShot) and PlayerFocusPredicted() + Player:FocusCastRegen(S.AimedShot:CastTime()) > Player:FocusMax() and not Player:Buff(S.SentinelsSight) then
```

**Comment by az1986** [comment]
can confirm this fix works 👍 

should push to live

**Comment by Kutikuti** [comment]
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/5aae92a227a828c58857d0eb331fe5f00f65f8b5
