### ISSUE TITLE
[Frost DK] Icons not showing

### ISSUE THREAD

**Issue by losccoy** [SimCMinMax/AethysRotation#113]
I might be doing something wrong but i only get the initial action on the frost DK.  Afterward it gives what looks like a placeholder icon

**Comment by losccoy** [comment]
![example](https://user-images.githubusercontent.com/35572031/35108499-5b4560da-fc39-11e7-8a45-e13206adf2fe.jpg)

**Comment by chrislopez24** [comment]
Show me your runes and rp(The complete image)

**Comment by losccoy** [comment]
![runes](https://user-images.githubusercontent.com/35572031/35165958-d5e054e4-fd15-11e7-9b57-27e256a6752d.jpg)

**Comment by losccoy** [comment]
not sure if you needed something else, let me know if so

**Comment by chrislopez24** [comment]
oh thats it, the rotation optimized for max level. (At 55 you dont have all talents, artifact weapon, etc)

**Comment by losccoy** [comment]
kk, so just level up and it should clear itself up.  thanks man!

**Comment by chrislopez24** [comment]
Youre welcome, thanks for taking the time to create the ticket
