### ISSUE TITLE
[Arcane] error

### ISSUE THREAD

**Issue by solitha** [SimCMinMax/AethysRotation#114]
Using 7.3.2.02-34-gbf1e485-alpha

98x AethysRotation_Mage\Arcane.lua:359: attempt to compare number with boolean
AethysRotation_Mage\Arcane.lua:359: in function <AethysRotation_Mage\Arcane.lua:328>
AethysRotation_Mage\Arcane.lua:452: in function `?'
AethysRotation\Main.lua:431: in function <AethysRotation\Main.lua:409>

Locals:
InCombatSkipped

**Comment by Kutikuti** [comment]
Fixed with https://github.com/SimCMinMax/AethysRotation/commit/c3ab5939d013d4b1bbeb99df1e410dbdfc8c1d51
