### ISSUE TITLE
[Disc Priest]

### ISSUE THREAD

**Issue by antisocialian** [SimCMinMax/AethysRotation#115]
While there is no rotation, the addon leaves the border for the main icon in the middle of the screen and it can't be interacted with. It goes away if I switch to shadow and stays away when i switch back to Disc, but is there every time I log in as Disc or reload the ui (after hiding it by switching to shadow and back).

In Discipline: https://i.imgur.com/W4ajExi.jpg
In Shadow: https://i.imgur.com/xC3MDyP.jpg(to show that it is the icons from this addon)

**Comment by ghr74** [comment]
That seems to be an issue with the masque support, I'll try to fix it ASAP. For the time being, you should be able to go to the masque settings and disable skinning for AethysRotation to fix it

**Comment by ghr74** [comment]
Should be fixed in https://github.com/SimCMinMax/AethysRotation/commit/b5585fc0472682d7e5272e950dffb3715a4fbd51 , thanks for the report!

**Comment by antisocialian** [comment]
👍 wow thanx for the fast fix!
