### ISSUE TITLE
[UH DK] pooling issue

### ISSUE THREAD

**Issue by TheaAngelica** [SimCMinMax/AethysRotation#116]
Firstly there is no AR.CDsON() check on the big CD's.
Then there is no check for AR.CDsON() for pooling on i.e clawing shadows and death coil. 

Would be easier to upload the file so you can look at it and compare, but I can't upload lua files here. Just ask me on discord.

Ankhy

**Comment by ghr74** [comment]
Hey,

if you've already made an updated file, feel free to submit it as a pull request. Also, you should be able to attach any kind of file here just fine.

Thanks for the report!

**Comment by chrislopez24** [comment]
As @ghr74 said, If you have any updated file you can contact us on discord or opening a pull request. Thanks!
