### ISSUE TITLE
[Fire Mage] dragon's breath

### ISSUE THREAD

**Issue by TheaAngelica** [SimCMinMax/AethysRotation#117]
Suggesting dragon's breath even tho target is not in range. (Without the legendary)

Ankhy

**Comment by ghr74** [comment]
Hey,

I've just fixed an issue that could cause this in situations where AoE mode is disabled. Besides that, I wasn't quite able to replicate this one - https://i.imgur.com/upEy0dS.jpg - this is about the farthest away that dragon breath will show for me and it hits. The range should be picked quite conservatively in fact. Could you send a screenshot/video of a scenario where this issue occured?
