### ISSUE TITLE
[Balance Druid] Error in spells

### ISSUE THREAD

**Issue by Mikehoncho47** [SimCMinMax/AethysRotation#118]
I'm playing a level 51 Balance Druid and the Rotation keeps telling me to use new moon. I don't have the ability to use new moon... obviously since I'm not level 100. I love the addon but can use it with my Balance Druid till this is corrected or someone tells me how to fix it my self.

**Comment by Kutikuti** [comment]
The rotations are optimised for max level. We can try to add condition for spells but the rotation will probably not be correct afterwards.
