### ISSUE TITLE
[Fire Mage] Issues / ST vs AOE

### ISSUE THREAD

**Issue by sHIrex** [SimCMinMax/AethysRotation#119]
1) Suggesting the cast of dragon breath without legendaries out of range.
2) Suggesting of hardcasting or instacasting of flamestrike at inappropriate times (like 1x target or boss) over Pyroblast. Adding onto that, sometimes with some specs i notice that single target spells will be prioritized when aoe spells would be more appropriate and the other way around. (Firestrike priority as told by the mage discord, https://i.imgur.com/7R3XgVF.png).
3) Suggesting the hardcasting of pyroblast without bracers or pre-casting in dungeons on repeated new targets.

**Comment by ghr74** [comment]
Hey,

first off, thanks for the report!
1.) I wasn't quite able to replicate this one - https://i.imgur.com/upEy0dS.jpg - this is about the farthest away that dragon breath will show for me and it hits. The range should be picked quite conservatively in fact. Could you send a screenshot/video of a scenario where this issue occured?

2.) Target counting can be finnicky for ranged specs - we have no way to predetermine the clustering of enemies, so if mobs stand idle to the side, but still in range, while you fight a different pack (or even the pack you're fighting is split up with ranged & melee mobs), we're somewhat limited to counting the total amount of enemies in your max range. One option would be to turn off AoE-Mode in such situations and use your instas on flamestrikes personally

3.) Pyroblast is the correct out-of-combat opener as pet simc APL and switching targets should work fine when staying in combat during that time (please report if not). As for dropping out of combat inbetween, we don't really have a way of telling whether your strategy will allow for the correct ooc opener (pyro) or require a shorter spell - however, the addon should skip the pyro opener suggestion on casting any spell or entering combat, so feel free to open with a fireball or other spell of your choice instead.

I have identified an issue with the Dragon Breath range restriction while AoE mode is disabled and will work on fixing it.

**Comment by sHIrex** [comment]
I would assume Dragon Breath Range on 1) was due to AoE Mode disabled since I did disable it after encountering the issues with the AoE Packs.

**Comment by sHIrex** [comment]
So my problem with 2) is that these enemies were not even in combat, say for example I was fighting in the shattered halls last boss (Warchief Kargath Bladefist) and he's alone there in his boss room, the only possible thing is a) missed enemy (rogues) in front hallway or inactive executioner in back hallway,. Enemies not partaking in fights after an encounter has started should not be identified by targeting logic afterwards, the easy problem to fix is you'd probably have to have an opener section defined that either shows the ST or AoE Spell with the highest priority before a battle has started (as an option?).

The hard problem would be identifying newly spawned trash in bosses and that would require to lean on open source things like BigWigs in boss encounters), but adding dependencies like that can be something unwanted. The Alternative would be to track everything from the perspective of a focus target (the tank), i.e everything in range of auto attacks is a cluster of enemies, everything outside of it can be considered not in a cluster. Is that something that is even trackable?

**Comment by Kutikuti** [comment]
The aoe issue for range is that we can't detect the range from one another because we can't have the position of the mob. So we can't detect cluster or separated mobs. As for in combat or not, we could include that possibility but sometimes you wan't to tag mobs that are not yet in combat with you so it would have to be a toggle that you change regularly...
