### ISSUE TITLE
[War Fury] LUA Error

### ISSUE THREAD

**Issue by Vilt-Coding** [SimCMinMax/AethysRotation#122]
![image](https://user-images.githubusercontent.com/23732193/35617357-3f62e43e-0678-11e8-8cb3-ba6eb59bc9b9.png)

Error I'm getting with fury, causes nothing to show up as suggestion other than execute when i have the fury for it.

Here's my gear 
![image](https://user-images.githubusercontent.com/23732193/35617415-6d3d9d9a-0678-11e8-9486-6dbd152f172d.png)
Fixed by unequipping t19.

Another issue is no suggestions showing when im hitting a dummy and its on very low hp, but that's not something you'd come across very often in the real game.

**Comment by Vilt-Coding** [comment]
Another question,

Could Ring of Collapsing Features get added as on-use item?

**Comment by Kutikuti** [comment]
fixed in https://github.com/SimCMinMax/AethysRotation/commit/99855bb53a65f3d90af9ccdbf2ddd41e13839a76

For items, we don't really support them
