### ISSUE TITLE
Debug Printed to Chat Window

### ISSUE THREAD

**Issue by Sinaloit** [SimCMinMax/AethysRotation#124]
The following line prints  out "ST2" to the chat window multiple times, this appears to be a debug print but should either be removed or changed to only print if some debug flag is on.

https://github.com/SimCMinMax/AethysRotation/blob/a5f79ebc5255d1c215056df5bbb6e7df79102e30/AethysRotation_Hunter/Survival.lua#L246

**Comment by Kutikuti** [comment]
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/859a6d8857ba051c9cfb434cad8e990d9d51b55b
