### ISSUE TITLE
Keybinds not showing up on one of my chars for all abilities.

### ISSUE THREAD

**Issue by Yaiklai** [SimCMinMax/AethysRotation#129]
On my Druid, every ability that is on my primary actionbar is missing the keybind, abilites not on my primary actionbar (same bar as stealth) show it though.

https://i.imgur.com/OJbqmAg.png

**Comment by Aethys256** [comment]
Should be fixed by https://github.com/SimCMinMax/AethysCore/commit/cd4b639f9a6e2c50ad9f31fe5cf3bbab42a43631 :)
