### ISSUE TITLE
Demonology request

### ISSUE THREAD

**Issue by solitha** [SimCMinMax/AethysRotation#130]
Could you add a check for Doom to see if it's a learned spell, for the lowbie users? It seems to work well enough otherwise.

**Comment by Glynnyx** [comment]
Hello,

Thank you for submitting the request, all feedback is greatly appreciated. The purpose of Aethys Rotation is to mirror what is displayed in the Simulation Craft APL to the best of our ability and the APL's there are for max level.

To avoid further confusion I updated the README.rmd to reflect this. 

Kind regards,
Glynny
