### ISSUE TITLE
Make a proper function to check for targets near your target, so aoe\cleave for ranged works correct

### ISSUE THREAD

**Issue by Ankhy** [SimCMinMax/AethysRotation#131]
Yeah, title. Would be sick to have a proper function for an enemy count around your target (or pets) so aoe\cleave for ranged works properly. Doing Cache.EnemiesCount[40] > 4 basically checks if there is more than 4 ppl in an 40 yard radius around you. Hardly helpful. I know a proper function is possible, but I have been out of the game for far too long to remember how I did it.

**Comment by Aethys256** [comment]
Not possible by the Blizzard API.
