### ISSUE TITLE
[BM Hunter] Counter shot 

### ISSUE THREAD

**Issue by Kenichiwo** [SimCMinMax/AethysRotation#132]
Counter Shot doesn't show up on interrupt.
Option toogled, even with sephu'z equiped.

Also, the sephuz's option won't stay toogled after reload/relog.

Thx for reading ^_-

**Comment by ghr74** [comment]
Hello and thanks for the report!
This should be fixed in https://github.com/SimCMinMax/AethysRotation/commit/319453370eed8b0ef797ce7dfb37531181d25644 .
Feel free to reopen if the issue persists.
