### ISSUE TITLE
[Monk WW] Recommending Ability Thats on Cooldown - Working as Intended?

### ISSUE THREAD

**Issue by Snichy** [SimCMinMax/AethysRotation#134]
Just found this addon and its exactly what Im looking for, however I have an issue that may or may not be solvable with some kind of option im missing: it is recommending an ability to cast that is on cooldown!  

I would have thought the whole purpose of this addon was to prevent this from happening and to recommend an ability that is actually available rather than one that isnt so maybe Im missing something in the options.  Or if the addon is calculating that it is still optimal to wait until the ability is off cooldown rather than casting something that isnt, I would thought there would be some kind of visual cue for that (greyed out, red gloss or even a cooldown text) but there isnt as far as I can see.

WW Monk btw :)

**Comment by Kutikuti** [comment]
What was the ability and the cooldown remaining ?

**Comment by Snichy** [comment]
Ive noticed it mostly with Rising Sun Kick, Chi Wave and Fists of Fury, when theres only maybe a couple of seconds left on cooldown (but with WW, its a fast pace and you have to cast different abilities quickly due to the mastery so its quite noticable), and also sometimes when it suggests Tiger Palm but theres not enough Energy.

**Comment by WhiteW84** [comment]
I am also leveling up a WW monk and I thought maybe it was because I wasn't at max level yet.  For me it is happening mainly on Rising Sun Kick and Fist of Fury.

**Comment by Hinalover** [comment]
This should be fixed with https://github.com/SimCMinMax/AethysRotation/commit/1c396f594c81db15d701b8731fdb2f526e076b6f

If there is still issues re-open and let me know.
