### ISSUE TITLE
thumbnail issues with BM hunter?

### ISSUE THREAD

**Issue by SkydiveGayGuy** [SimCMinMax/AethysRotation#135]
on my 103 BM hunter it generally has me cast kill command, dire beast, dire beast, then a weird thumbnail pops up, it almost looks like Exhilaration but it has the word POOL at the bottom of the thumbnail. am I just such a newb that I'm unaware of the spell? or are my thumbnails glitching

**Comment by ghr74** [comment]
"Pooling" is a term often used to express "waiting with a purpose", refer to https://wow.gamepedia.com/Resource_pooling . When pool shows, it essentially means "wait". Not an issue, but thanks for the report.
