### ISSUE TITLE
[Paladin] LUA Error

### ISSUE THREAD

**Issue by Ykkris** [SimCMinMax/AethysRotation#136]
Hey, there is a LUA error in the last alpha build

> Message: ...erface\AddOns\AethysRotation_Paladin\Retribution.lua:210: attempt to index field 'Crusade' (a boolean value)
> Time: 02/26/18 12:01:48
> Count: 392
> Stack: ...erface\AddOns\AethysRotation_Paladin\Retribution.lua:210: attempt to index field 'Crusade' (a boolean value)
> Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
> [C]: ?
> ...erface\AddOns\AethysRotation_Paladin\Retribution.lua:210: in function `?'
> Interface\AddOns\AethysRotation\Main.lua:432: in function <Interface\AddOns\AethysRotation\Main.lua:410>
> 
> Locals: errorMessage = "...erface\AddOns\AethysRotation_Paladin\Retribution.lua:210: attempt to index field 'Crusade' (a boolean value)"
> DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
> MESSAGE_TYPE_ERROR = 0

**Comment by ghr74** [comment]
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/3d58e70190fb2400342fc772bbdb4be900bdfee1 . Thanks for the report!
