### ISSUE TITLE
[Frost DK] **Cold Heart**...Please Fix.

### ISSUE THREAD

**Issue by Sonovahlich** [SimCMinMax/AethysRotation#137]
Hi, It's come to my attention that the rotation, although flawless imo, Needs to give us the option to take Cold Heart out of the rotation or, just taken out completely. 
I know that, myself and most DK's I know, do their best to use it, only at 20 stacks, particularly when Pillar of Frost is active, etc.
However, the rotation is sitting on Cold Heart, even when it has 3 stacks (useless at 3 stacks imo) and it just holds up the rotation helper, which costs valuable DPS when you've fudged up your rotation and the helper is sitting on Cold Heart.

The ability to turn this spell on or off, would be fantastic, or just remove it completely and leave it to the player's discretion please! :)

**Comment by Sonovahlich** [comment]
I'm sorry,  maybe I stated it wrong.  I was just using the example of 3
stacks. The point was,  it places it in the rotation prior to 20 stacks
and even under 10 sometimes.
It seems as though,  if it pops up at 20 and you ignore it,  as in, wait
for a more opportune moment,  it then places it back in the rotation after
you use it,  while at an underwhelming amount of stacks. Which,  if you're
not paying attention,  causes you to use it at a rather weak level and even
without pillar up.

Whereas I would consider "building stacks" as a similar action to CD, since
they are both mechanic based on "time".
If not putting it on the rotation as a CD, maybe make it only present it
self once Pillar of Frost is active?
At least,  that way,  it lines itself up with the Pillar of Frost CD.
Which,  it has been stated in multiple communities,  that building 20
stacks of cold heart,  takes about the same amount of time as Pillar of
Frost (within a few seconds) which would in turn,  place it in the rotation
at the most opportune moment.

Just my two cents :)
Thanks for the quick response!

**Comment by Glynnyx** [comment]
Ah, I see where you're coming from. 

The addon is a replica of what is occurring in Simulationcraft. The aim of the addon is to provide you with a visual of what will yield the highest DPS possible in every scenario. 

The use of Chains of Ice with Cold Heart is accounted for on many levels, it has its own set of functions to perfectly cater for this. I am certain when comparing Simulationcraft to our addons interpretation of this Actions List that the scenarios are covered. That information can be found here: https://github.com/SimCMinMax/AethysRotation/blob/master/AethysRotation_DeathKnight/Frost.lua#L420

If you have solid data to say either Simulationcraft or we are wrong I will happily investigate but as for now what we have in the addon is exactly what is written in the Actions List.

**Comment by chrislopez24** [comment]
If you have any apl improvement you can find us on discord. Thanks!
