### ISSUE TITLE
[UH DK] Infected Claws Bug

### ISSUE THREAD

**Issue by LeighMetz** [SimCMinMax/AethysRotation#142]
Hi Guys

Just making you aware of a bug with unholy dk, if you have cooldowns turned off and are using the infected claws talent, it will not tell you to use death coil anymore.

**Comment by chrislopez24** [comment]
Hi! thanks for taking the time to open the issue!

I've been trying to reproduce your issue but for me its suggesting Death coil with CDs turned off. Im using the standard build with DA and Cold Heart + Shoulders (taking Infected claws instead of SI)
What version of the addon are you using? Does it gives you any lua error? if so, can you paste it here?

**Comment by LeighMetz** [comment]
Hi Chris

Sorry i'll try and explain this in more detail - perhaps there is some confusion on my part as to how the addon is suppose to function.

So when i'm playing SI build with cooldowns on, if i have all my cooldowns up (army, dark arb, dark trans) it comes up with a  "pool" icon instead of death coil, which i dont understand. I turned cooldowns off and it no longer comes up with pool and suggests deathcoil even with my cooldowns ready which is perfect for me.

Now with playing infected claws, again, with cooldowns turned on and cooldowns ready to go it just comes up with pool again. If i turn cooldowns off if just comes up with neither now, no pool or death coil. The only time it functions correctly for me in this situation is once i used my armys, da etc and there on cooldown then it will suggest death coil. 

Is there not a way that i can use infected claws have cooldowns turned off and it function the same way as SI with cooldowns off?

I have the latest version and no lua errors.

Thanks

**Comment by LeighMetz** [comment]
How do i use this update?

**Comment by chrislopez24** [comment]
If youre using Twitch client, just choose "alpha" version in AethysCore and AethysRotation and update

**Comment by LeighMetz** [comment]
I tried it unfortunately it didn't seem to fix it for me

**Comment by chrislopez24** [comment]
The problem is because that its trying to suggest to wait for army, do you have t20?

**Comment by LeighMetz** [comment]
I do have yes

**Comment by LeighMetz** [comment]
oh sorry no i don't, i thought t20 was the latest tier set, i have the one from ant and its still happening

**Comment by LeighMetz** [comment]
This still isnt fixed, just letting u guys know.

**Comment by Randomrambo** [comment]
I am also having this issue with "Infected Claws" talented. Issue is 100% still there.

**Comment by chrislopez24** [comment]
https://github.com/SimCMinMax/AethysRotation/commit/df9bbe8348edeadd4178073531a6624400448dfb should fix it, please confirm

**Comment by Randomrambo** [comment]
Confirmed, working now.
