### ISSUE TITLE
[Enhancement] PoolFocus in rotation

### ISSUE THREAD

**Issue by ZeroToInsane** [SimCMinMax/AethysRotation#143]
Hi AethysRotation Team,

while the rotation from my enhancement shaman i always get an icon which looks like a dragonball fighter. I used the debug option and the ability i should cast is called pool focus. I have no idea what kind of ability it should be. Is this a bug?

Best regards
ZeroToInsane

**Comment by ghr74** [comment]
"Pooling" is a term often used to express "waiting with a purpose", refer to https://wow.gamepedia.com/Resource_pooling . When pool shows, it essentially means "wait". Not an issue, but thanks for the report.

**Comment by ZeroToInsane** [comment]
Thanks for the fast answer.

**Comment by WorgenPaws** [comment]
The issue I'm having however is that the Pool icon consistently shows constantly. No other icons show up.

**Comment by lithium720** [comment]
@WorgenPaws check https://github.com/herotc/hero-rotation#supported-rotations
It has not been updated or touched yet for BfA. ETA: Soon.
