### ISSUE TITLE
Elemental Shaman: Gnawed Thumb Ring always shows to use

### ISSUE THREAD

**Issue by Fraktyl** [SimCMinMax/AethysRotation#144]
If you have the Gnawed Thumb ring equipped it will always show that as the next skill even if the ring is on cooldown.

**Comment by ghr74** [comment]
Hey and thanks for the report.
This should be fixed in https://github.com/SimCMinMax/AethysRotation/commit/c3750845bbffb174b91b9b84ce944d8d6125bfe5 . Please let us know if it persists.
