### ISSUE TITLE
Suggestion: mage shield in solo mode

### ISSUE THREAD

**Issue by Barleduq** [SimCMinMax/AethysRotation#146]
All 3 mage specs have shields. I noticed that the frost spec has the button for the elemental come up. Would it be reasonable to have an option to have the mage shield come up as a suggestion? at the start of combat (the first thing suggested) and on cool down after that?  When I was first learning to play squishy mage (boosted toon at teh start of WoD) I made that part of my own rotation - shield, start with a slow cast, then use whatever was available, and hit Shieldtronic Shield if I had them, if the shield went down from damage before I coudl refresh it. Obviously you can't take the Shieldtronic Shield into account (and it's not useful anymore anyway) but the base shield would be useful, especially when trying to prioritize survivability?   Thank you for doing all the crazy work for coding these things!

**Comment by Glynnyx** [comment]
Hello,

Thank you for taking the time to submit feedback. 

The purpose of the addon is to provide you with the highest possible damaging rotation and casting shield at all, let alone on cooldown simply doesn't give you more damage. I understand the argument "you can't do DPS if you're dead" sure, but there is an assumption to be made that you are not going to die. 

To go in to a little more detail, lets says we did add it to cast shield on CD, the minute buff (from Ice Barrier) went completely untouched for the entire time and you recast, that wasted a full global cooldown casting Ice Barrier which could have been used on a Frostbolt that granted a Brain Freeze etc.

We're trusting the users to make their own decisions on defensive cooldowns as this is the optimal use for them, you should be deciding when to use them yourself to maximize up time on the boss and do as much damage as possible. 

Hope this helps you out a little bit. 

Thanks,
Glynny
