### ISSUE TITLE
[Balance Druid] Stellar Drfit movement

### ISSUE THREAD

**Issue by Radiskillz** [SimCMinMax/AethysRotation#150]
The lvl 100 balance talent "Stellar Drift" allows casting whilst moving while in the area of your own starfall. This is shown by the buff "Stellar Drift" whilst inside the area. Aethys doesn't currently realise i can cast whilst moving, and still suggests using only instant spells whilst moving.

**Comment by Radiskillz** [comment]
The lvl 100 balance talent "Stellar Drift" allows casting whilst moving while in the area of your own starfall. This is shown by the buff "Stellar Drift" whilst inside the area. Aethys doesn't currently realise i can cast whilst moving, and still suggests using only instant spells whilst moving.

**Comment by Kutikuti** [comment]
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/938801e5e703922ca3be0500156f46bc43533156

The buff didn't have the same id as the talent
