### ISSUE TITLE
Build in talents and gear presets suggestions

### ISSUE THREAD

**Issue by mspykerez** [SimCMinMax/AethysRotation#152]
I don't know if this is out of the scope of the addon or not but could you make it so the addon suggests the best talents and gear to use ? Like having a preset of the best talents and BIS gear we should aim for build in as a basic reference guide ?

Also I would like the idea if this addon would adapt the rotation for low lvl characters as a means to learn them while we lvling up.

**Comment by Kutikuti** [comment]
It would be a nightmare to maintain and a bit out of the scope of the addon. Some website do this very well already.

For leveling, that's not planned currently
