### ISSUE TITLE
Vendetta showed when just target at a new enemy

### ISSUE THREAD

**Issue by mizone** [SimCMinMax/AethysRotation#158]
please check the opener of a battle. Vendetta showed when just target at a new enemy.

    if S.Vendetta:IsCastable() and (not S.Exsanguinate:IsAvailable() or Target:DebuffP(S.Rupture)) then
      if AR.Cast(S.Vendetta, Settings.Assassination.OffGCDasOffGCD.Vendetta) then return "Cast Vendetta"; end
    end

**Comment by Mystler** [comment]
This is correct. Vendetta sims best when used on pull, and yes, I know you will waste the energy gain from Urge to Kill.
