### ISSUE TITLE
WeakAuras

### ISSUE THREAD

**Issue by DSSGFX** [SimCMinMax/AethysRotation#160]
I was wondering if there is anyway to send a trigger to WeakAuras so I can implement it with my aura setup. For example AethysRotation main window recommended spell is tigers palm then trigger aura. Im wanting to setup audio ques and key glows to help me out. My script skills are pretty bad but if im sent in the right direction I can usually figure it out.

**Comment by aethys256** [comment]
@capullo is right, it's always possible to override anything from the addon to make it as you want. Although, keep in mind that it is better for the community to pull request those features so it can be built-in in the addon.
For example, key glows might be something that could interest other peoples.
