### ISSUE TITLE
[Arcane] Bug in Arcane with 4-piece T21

### ISSUE THREAD

**Issue by swaj** [SimCMinMax/AethysRotation#164]
When I got 4-piece on my Arcane mage, I started getting a ton of Lua errors from AethysRotation.  The stack trace looks like this:

```
3223x AethysCore\Class\Unit\Aura.lua:43: attempt to index local 'Spell' (a nil value)
AethysCore\Class\Unit\Aura.lua:43: in function `Buff'
AethysCore\Class\Unit\Aura.lua:90: in function `BuffRemains'
AethysCore\Class\Unit\Aura.lua:120: in function `BuffDownP'
AethysRotation_Mage\Arcane.lua:283: in function <AethysRotation_Mage\Arcane.lua:223>
AethysRotation_Mage\Arcane.lua:448: in function `?'
AethysRotation\Main.lua:432: in function <AethysRotation\Main.lua:410>

Locals:
InCombatSkipped
```

I found the offending line here:

https://github.com/SimCMinMax/AethysRotation/blob/57c2228b4caa771abc8b5e37156ea3fb5d52360c/AethysRotation_Mage/Arcane.lua#L283

The problem is that `S.ExpandingMindBuff` does not exist.  When corrected to `S.ExpandingMind` the errors are resolved.

I just wanted to share.  Cheers! :)

**Comment by Glynnyx** [comment]
Issue fixed in latest commit. https://github.com/SimCMinMax/AethysRotation/commit/8d1bab6b4293f851cdcfcbfd399dfb2ce40f7fff
