### ISSUE TITLE
UH DK - Still suggesting Cooldowns

### ISSUE THREAD

**Issue by Randomrambo** [SimCMinMax/AethysRotation#171]
UH DK is still suggesting to use cool-downs when I have it disabled. The "c" is red. Suggesting to use DA, Apoc and so on

**Comment by chrislopez24** [comment]
try https://github.com/SimCMinMax/AethysRotation/commit/2f606ab8c71c40da44e325318326367fb94369ac

couldnt test it ingame, feel free to text me in discord if anything is not working
