### ISSUE TITLE
[Havoc]  BfA 

### ISSUE THREAD

**Issue by Darkmoded** [SimCMinMax/AethysRotation#179]
Line 232 can return true when Felblade is not talented

  -- felblade,if=fury<40|(buff.metamorphosis.down&fury.deficit>=40)
    if S.Felblade:IsCastable(S.Felblade) and Player:Fury() < 40 
      or (not Player:BuffP(S.MetamorphosisBuff) and Player:FuryDeficit() >= 40) then
      if AR.Cast(S.Felblade) then return "Cast Felblade"; end
    end

**Comment by EvanMichaels** [comment]
Sorry, not seeing this at all. S.Felblade:IsCastable should never return true if it's not talented, and I'm not seeing it suggested when I am spec'd into DA or Blind Fury.

**Comment by Darkmoded** [comment]
(S.Felblade:IsCastable(S.Felblade) and Player:Fury() < 40)  OR
(not Player:BuffP(S.MetamorphosisBuff) and Player:FuryDeficit() >= 40)  << This will trigger True does not check for Fleblade
