### ISSUE TITLE
[GUI] Config Panel

### ISSUE THREAD

**Issue by Aethys256** [SimCMinMax/AethysRotation#30]
Make options available in WoW built-in config panels.

**Comment by Aethys256** [comment]
Available in @SimCMinMax/aethyscore since https://github.com/SimCMinMax/AethysCore/commit/188c90afb5a0c8bb9caba0b5992ccb4529ffe414 and in @SimCMinMax/aethysrotation since https://github.com/SimCMinMax/AethysRotation/commit/e08fcb45d3a333093600dc0454d872aebe0b0afb.

**Comment by Kutikuti** [comment]
Added Scale, Lock/Unlock and Reset anchor to settings in https://github.com/SimCMinMax/AethysRotation/commit/3c5992680f42ddf54f622f2818bbf3bfcdc35d20 and https://github.com/SimCMinMax/AethysRotation/commit/7ac1d7d9bf6f8c66d2f744e57a85ba1824190d92
