### ISSUE TITLE
[UI] Key Bindings

### ISSUE THREAD

**Issue by shadofall** [SimCMinMax/AethysRotation#33]
would it be possible to get and display the ability keybinding similar to how ovale can? i understand it could prob only be done with Action Bars that use the blizzard keybinds (IE Default/Elv and prob a few others i dont know). would be tremendously helpfull on alts that people havent quiet remembered whats keybinded where.

**Comment by Aethys256** [comment]
I like the idea, I'll see what I can do for 7.3.

**Comment by mrminus** [comment]
I'd like this as well, in case you're looking for support on implementing. Ideally it would just pull the key binding off the key. Hekili (a shaman dps rotation addon like yours) does a good job of this.

**Comment by mrminus** [comment]
Hi @Aethys256 , with 7.3 released do you think you'll have time for key binding addition? I know I would appreciate it being there.  thanks.

**Comment by skasch** [comment]
Merged skasch-keybinds branch into master.
