### ISSUE TITLE
Beast Mastery

### ISSUE THREAD

**Issue by Duffroxwow** [SimCMinMax/AethysRotation#36]
Message: ...erface\AddOns\AethysRotation_Hunter\BeastMastery.lua:198: attempt to compare nil with number
Time: 07/19/17 06:29:12
Count: 151
Stack: ...erface\AddOns\AethysRotation_Hunter\BeastMastery.lua:198: attempt to compare nil with numberInterface\SharedXML\SharedBasicControls.lua:189: in function <Interface\SharedXML\SharedBasicControls.lua:187>
Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: ?
...erface\AddOns\AethysRotation_Hunter\BeastMastery.lua:198: in function `?'
Interface\AddOns\AethysRotation\Main.lua:292: in function <Interface\AddOns\AethysRotation\Main.lua:282>

Locals: errorTypeCVar = "scriptErrors"
warnType = false
msg = "...erface\AddOns\AethysRotation_Hunter\BeastMastery.lua:198: attempt to compare nil with number"
messageType = 0
hideErrorFrame = false
IsErrorCVarEnabled = <function> defined @Interface\SharedXML\SharedBasicControls.lua:183

**Comment by Aethys256** [comment]
Thanks for the report, fixed it.
