### ISSUE TITLE
[Rotation] Subtlety: DFA w/ AoE Disabled

### ISSUE THREAD

**Issue by Bareno** [SimCMinMax/AethysRotation#38]
The rogue / subtlety rotation never seems to suggest death from above if you are talented into it.

**Comment by Aethys256** [comment]
Are AoE and CDs enabled ?

**Comment by Bareno** [comment]
Hm, AoE no but CDs yes, but DFA is something you would want to use in ST as well, so I don't see why it shouldn't show up if you have AoE disabled

**Comment by Aethys256** [comment]
Yes I need to handle those things differently, someone already told me on Curse.
Thing is, my available time is very tiny atm :/
Will try to do it this week-end.

**Comment by scarface646** [comment]
salut vu que tu es français et que mon anglais et incompréhensible je viens vers toi pour la même chose dfa n'est jamais propose en finish il propose tout le temps éviscération voila merci a toi pour l addon

**Comment by scarface646** [comment]
How to update the addon with the link
