### ISSUE TITLE
AethysRotation

### ISSUE THREAD

**Issue by AmazingJD** [SimCMinMax/AethysRotation#44]
If AethysRotation is enabled, i can't join random bgs. I click the button but nothing happens. I tested it by enabled all other Addons but AethysRotation, so I can say for sure that this Addon has a little bug. 

I like this Addon, please fix it :D

-Greets

**Comment by chrislopez24** [comment]
Hi, Thanks for contact us, but we need the following:
Version of the Addon :
Detailed information about what is happening:
Lua errors if theres any (install bugsack/buggraber) and paste the error message here or in pastebin.com
