### ISSUE TITLE
[Rotation] Subtlety: DfA Vanish Conditional Issues

### ISSUE THREAD

**Issue by EvanMichaels** [SimCMinMax/AethysRotation#45]
When the APL was updated a few weeks ago, a Vanish condition was added to the Sub DfA conditionals. This causes problems with DfA usage with the cooldown button disabled as Vanish is not used and thus DfA will never be suggested even when appropriate.

The "or not S.Vanish:CooldownUp()" conditional in the DfA line should be altered to consider AR.CDsON()

As an additional note about this conditional in general:

Given the relatively small gain of this Vanish conditional in optimal play (very, very small gain, even at high iterations--need to be at 0.03% error to see a difference within the margin of error,) it may be worth considering removing this Vanish conditional for AER. 

Even missing a single Vanish macro GCD can result in DfA being delayed very significantly, which is not a problem sims have (as they flawlessly execute Vanish sequences) but is definitely likely when players are having to react to suggestions quickly. I'm also not sure this is a gain at all without the Shoulders--simming at 54k iterations with my character without shoulders, removing "!talent.dark_shadow.enabled|!cooldown.vanish.up" both profiles are still within the margin of error.

With the T20M DfA profiles, there is still no difference at 0.05% and at 65k iterations actually seemed to show a 2k DPS *loss* over the altered APL with a DPS error of 410. So I think this conditional in general may need re-evaluation.

Regarding AER specifically: since the Vanish macro only shows up in very specific conditions, it's relatively easy to accidentally skip and then not see DfA suggested for a full cycle--almost certainly a larger DPS loss than not having the conditional, but SimC likely never encounters this condition.

Simming with a special conditional, it appears that even one mistaken Vanish GCD skip is worth about an 8k DPS loss for my character, which seems like really poor risk/reward ratio (considering the conditional has no gain for me anyway!)

**Comment by mrdmnd** [comment]
I agree. If you want to put a commit / PR together, I'll merge it.

**Comment by Mystler** [comment]
Thanks for the report. I looked into and you seem to be right. Pushed changes for both simc and AER. https://github.com/SimCMinMax/AethysRotation/commit/1bce9264ba788c59c95da40f27043cfe338412ff
