### ISSUE TITLE
LUA Error After completing a quest

### ISSUE THREAD

**Issue by erxx** [SimCMinMax/AethysRotation#47]
> x [ADDON_ACTION_BLOCKED] AddOn 'AethysRotation_Rogue' tried to call the protected function '<unnamed>:Hide()'.
> !BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
> [C]: in function `Hide'
> FrameXML\WorldMapActionButton.lua:58: in function `Clear'
> FrameXML\WorldMapActionButton.lua:67: in function `Refresh'
> FrameXML\WorldMapActionButton.lua:19: in function `SetMapAreaID'
> FrameXML\WorldMapFrame.lua:1341: in function `WorldMapFrame_Update'
> FrameXML\WorldMapFrame.lua:2873: in function `WorldMapFrame_UpdateMap'
> FrameXML\WorldMapFrame.lua:451: in function <FrameXML\WorldMapFrame.lua:435>
> [C]: ?
> [C]: in function `SetMapToCurrentZone'
> FrameXML\WorldMapFrame.lua:381: in function <FrameXML\WorldMapFrame.lua:360>
> [C]: in function `Show'
> FrameXML\UIParent.lua:2421: in function `SetUIPanel'
> FrameXML\UIParent.lua:2223: in function `ShowUIPanel'
> FrameXML\UIParent.lua:2133: in function <FrameXML\UIParent.lua:2129>
> [C]: in function `SetAttribute'
> FrameXML\UIParent.lua:2915: in function `ShowUIPanel'
> FrameXML\UIParent.lua:2899: in function `ToggleFrame'
> FrameXML\WorldMapFrame.lua:263: in function <FrameXML\WorldMapFrame.lua:235>
> [C]: in function `ToggleWorldMap'
> [string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>
> 
> Locals:

**Comment by Kutikuti** [comment]
Same as https://github.com/SimCMinMax/AethysRotation/issues/54

**Comment by Aethys256** [comment]
Fixed in https://github.com/SimCMinMax/AethysCore/commit/f6c3cd274e0237612cf26ff0e2536fa74a7f368e :)
