### ISSUE TITLE
Frost DK Errors 7.3

### ISSUE THREAD

**Issue by JDP2012** [SimCMinMax/AethysRotation#48]
Frost DK - 3/2/1/3/2/3/1

Errors below

AethysRotation_DeathKnight\Frost.lua:480: attempt to index field 'S' (a nil value) AethysRotation_DeathKnight\Frost.lua:339: attempt to index field 'FreezingFog' (a nil value)
AethysRotation_DeathKnight\Frost.lua:339: in function <AethysRotation_DeathKnight\Frost.lua:329>
AethysRotation_DeathKnight\Frost.lua:487: in function `?'
AethysRotation\Main.lua:296: in function <AethysRotation\Main.lua:286>

**Comment by chrislopez24** [comment]
Thanks for reporting the issue, should be fixed If you download the github version
