### ISSUE TITLE
[Windwalker] Serenity issue

### ISSUE THREAD

**Issue by williamfn** [SimCMinMax/AethysRotation#51]
When talenting into Serenity (level 100), after activating that skill the addon only shows the artifact weapon as rotation even when it is on cooldown.
The addon get stuck with that skill and only changes to Tiger Palm when i have less than 2 combo points. After getting 2 or more combo points it goes back to weapon skill stuck.

Talents im using when it happens:
- Eye of the tiger
- Chi Torpedo
- Ascension
- Leg Sweep
- Healing Elixir
- Hit Combo
- Serenity

**Comment by shadofall** [comment]
any progress on this bug?

**Comment by Kutikuti** [comment]
https://github.com/SimCMinMax/AethysRotation/commit/cacc964c82564a32011b1d22a8c1c9bb629c7909 (in the last realease) correct the issue ?

**Comment by shadofall** [comment]
seems to be ok now
