### ISSUE TITLE
Fix the dropdown Taint

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/AethysRotation#54]
LUA error with the dropdown in the settings. Previously discussed on Discord.

AN example of errors : 
2x [ADDON_ACTION_BLOCKED] AddOn 'AethysRotation_Rogue' tried to call the protected function 'CompactPartyFrame:unusedFunc()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `unusedFunc'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:160: in function `CompactRaidFrameContainer_LayoutFrames'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
InCombatSkipped

Krich on discord : 
I talked with one guy at wowui channel on irc
And seems like every addon that adds a dropdown menu on the esc-interface panel taints the ui If you access the settings in combat
I tested with Hekili and voila, error message
And it always taints compactraidframe
Yeah, some guy confirmed it to me
Apparently , frames can't be created or destroyed in the secure enviroment while in combat, so once you try to create the actual drop down, it taints, then any call made after that taints as well
because a dropdown works by creating a new frame when the drop down shows, it can't do that in combat without tainting
Solutions... Create our own lib, or using WoWAce library which cares about those stuff
Well we only need to create a lib and use functions from
EasyMenu.lua, UIDropDownMenu.lua and UIDropDownMenuTemplates.xml
Frames , tables and variables
And renamed everything
There was a guy who Apparently works for blizzard and linked me this
http://www.wowinterface.com/downloads/info22630-NoTaintUIDropDownMenu.html

**Comment by Aethys256** [comment]
Fixed in https://github.com/SimCMinMax/AethysCore/commit/f6c3cd274e0237612cf26ff0e2536fa74a7f368e :)
