### ISSUE TITLE
Dk Frost KM proc

### ISSUE THREAD

**Issue by bloodess** [SimCMinMax/AethysRotation#55]
Hi ! 
It's not an issue, but in frost, some KM proc is used on Obliterate instead of Frostscythe (if you've got the talent).

And if you've got the talent Frostscythe, you must use KM proc on it even on single target.

I hope I was clear enough, if not, feel free to ask me.

P.S : Sorry for my bad english :)

**Comment by chrislopez24** [comment]
Obliterate is used when you are about of capping runes as the APL says. If obliterate is suggested in other situation, please let me know giving more information

**Comment by bloodess** [comment]
Ok then, my bad.
I will try to focus on obliterate If it's suggested in other situation. But I don't think so.

Thanks a lot
