### ISSUE TITLE
Addon erroring out - not loading at all

### ISSUE THREAD

**Issue by sinjinns** [SimCMinMax/AethysRotation#58]
Updated to the latest version with Twitch - upon logging into the game I get the error 1x AethysRotation\Main.lua:145: Usage: AethysRotation_MainFrame:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
*full error text* 
1x AethysRotation\Main.lua:145: Usage: AethysRotation_MainFrame:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
[C]: in function `SetPoint'
AethysRotation\Main.lua:145: in function <AethysRotation\Main.lua:131>

Locals:
(*temporary) = AethysRotation_MainFrame {
 0 = <userdata>
 Lock = <function> defined @AethysRotation\Main.lua:95
 ResizeButtons = <function> defined @AethysRotation\Main.lua:60
 Unlock = <function> defined @AethysRotation\Main.lua:79
 ResizeUI = <function> defined @AethysRotation\Main.lua:38
}
(*temporary) = nil
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
}
(*temporary) = nil
(*temporary) = nil

Using any /aer command results in further errors. /aer unlock gives 1x AethysRotation\UI.lua:155: attempt to get length of field 'Part' (a nil value)
*full error text*
1x AethysRotation\UI.lua:155: attempt to get length of field 'Part' (a nil value)
AethysRotation\UI.lua:155: in function `HideParts'
AethysRotation\UI.lua:40: in function `ResetIcons'
AethysRotation\Main.lua:81: in function `Unlock'
AethysRotation\Core.lua:153: in function `?'
FrameXML\ChatFrame.lua:4512: in function <FrameXML\ChatFrame.lua:4459>
[C]: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4180: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4216: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = AethysRotation_MainIconFrame {
 ChangeIcon = <function> defined @AethysRotation\UI.lua:108
 Init = <function> defined @AethysRotation\UI.lua:92
 CooldownFrame = AethysRotation_MainIconCooldownFrame {
 }
 SetCooldown = <function> defined @AethysRotation\UI.lua:115
 SetupParts = <function> defined @AethysRotation\UI.lua:136
 InitParts = <function> defined @AethysRotation\UI.lua:118
 TempTexture = <unnamed> {
 }
 HideParts = <function> defined @AethysRotation\UI.lua:154
 0 = <userdata>
 texture = <unnamed> {
 }
}
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of field 'Part' (a nil value)"

/aer toggle gives 1x AethysRotation\UI.lua:449: attempt to index field 'Button' (a nil value)
*full error text*
1x AethysRotation\UI.lua:449: attempt to index field 'Button' (a nil value)
AethysRotation\UI.lua:449: in function `UpdateButtonText'
AethysRotation\Core.lua:150: in function `?'
FrameXML\ChatFrame.lua:4512: in function <FrameXML\ChatFrame.lua:4459>
[C]: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4180: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4216: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = AethysRotation_ToggleIconFrame {
 0 = <userdata>
 UpdateButtonText = <function> defined @AethysRotation\UI.lua:447
 Init = <function> defined @AethysRotation\UI.lua:318
 ResetAnchor = <function> defined @AethysRotation\UI.lua:372
 AddButton = <function> defined @AethysRotation\UI.lua:377
}
i = 3
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Button' (a nil value)"

**Comment by Aethys256** [comment]
As said on Curse, try to delete AER savedvariables (AethysCore & AethysRotation) to see.

**Comment by sinjinns** [comment]
Which savedvariables? the one in worldofwarcraft/wtf/account/XXX/savedvariables? there's aethyscache.lua aethyscache.lua.bak aethyscore.lua aethyscore.lua.bak aethysrotation.lua and aethysrotation.lua.bak
All of those? 

    On Monday, 16 October 2017, 14:26, Quentin Giraud <notifications@github.com> wrote:
 

 As said on Curse, try to delete AER savedvariables (AethysCore & AethysRotation) to see.—

**Comment by Aethys256** [comment]
All of them while having the game closed.
Be sure to be on 7.3.0.02 for AethysCore and 7.3.0.03 for AethysRotation.

**Comment by sinjinns** [comment]
Ok, I logged into Twitch, selected Delete for both, had it do the savedvariables as well. Reinstalled and made sure it was 7.3.0.02 and 7.3.0.03. As soon as I logged in the buttons aren't there and it gave the following error -
1x AethysRotation\Main.lua:244: Usage: GetSpecializationInfo(specIndex[, isInspect[, isPet[, inspectTarget[, sex]]]])[C]: in function `GetSpecializationInfo'AethysRotation\Main.lua:244: in function `PulseInit'AethysRotation\Main.lua:178: in function <AethysRotation\Main.lua:175>
Locals:(*temporary) = nil 

    On Monday, 16 October 2017, 19:31, Quentin Giraud <notifications@github.com> wrote:
 

 All of them while having the game closed.
Be sure to be on 7.3.0.02 for AethysCore and 7.3.0.03 for AethysRotation.—

**Comment by Aethys256** [comment]
May you try with every addon disabled to see if the error still occurs ?

**Comment by sinjinns** [comment]
Ok, I turned off all the addons except for Aethys Cache, Core, Rotation, Rogue and BugGrabber so I see any errors. There wasn't one. I reloaded all my addons 1 at a time to see if it caused it to error out doing a reloadui after each one, none did. I exited the game completely and logged back in, and it hasn't errored out yet. I have no idea what's going on now. 

    On Monday, 16 October 2017, 20:40, Quentin Giraud <notifications@github.com> wrote:
 

 May you try with every addon disabled to see if the error still occurs ?—

**Comment by Aethys256** [comment]
Indeed, that's really weird :)
Closing the issue for now, let me kow if you do have again the issue and what addon is causing it.

**Comment by sinjinns** [comment]
It happened again. I logged on the DH, played for a little bit then switched back to my rogue and got the same error when I logged in. You can leave the ticket closed, I appreciate the help but the addon just seems way too problematic =(  

    On Monday, 16 October 2017, 21:15, Quentin Giraud <notifications@github.com> wrote:
 

 Closed #58.—
