### ISSUE TITLE
Elemental Shaman Error

### ISSUE THREAD

**Issue by chatmanm2** [SimCMinMax/AethysRotation#61]
Message: Interface\AddOns\AethysRotation_Shaman\Elemental.lua:272: attempt to compare boolean with number
Time: 10/18/17 16:34:15
Count: 1
Stack: Interface\AddOns\AethysRotation_Shaman\Elemental.lua:272: attempt to compare boolean with number
[C]: ?
Interface\AddOns\AethysRotation_Shaman\Elemental.lua:272: in function `?'
Interface\AddOns\AethysRotation\Main.lua:300: in function <Interface\AddOns\AethysRotation\Main.lua:290>

I know it's still a WIP, however I figured this might help push it along a little. Looks like it might run into this same error further down. This just happens to be the Ascendance part, there's the same code for Ice Fury and Lightening Rod.

**Comment by chrislopez24** [comment]
fixed in https://github.com/SimCMinMax/AethysRotation/commit/559c4d31242ba9d72780efb6282fb973f7e5eff0

thanks for the report
