### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by Greaselugnut** [SimCMinMax/AethysRotation#62]
Date: 2017-10-19 15:35:46
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AethysRotation\Main.lua line 145:
   Usage: AethysRotation_MainFrame:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
Debug:
   [C]: SetPoint()
   AethysRotation\Main.lua:145:
      AethysRotation\Main.lua:131
Locals:
(*temporary) = AethysRotation_MainFrame {
 0 = <userdata>
 Lock = <function> defined @Interface\AddOns\AethysRotation\Main.lua:95
 ResizeButtons = <function> defined @Interface\AddOns\AethysRotation\Main.lua:60
 Unlock = <function> defined @Interface\AddOns\AethysRotation\Main.lua:79
 ResizeUI = <function> defined @Interface\AddOns\AethysRotation\Main.lua:38
}
(*temporary) = nil
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil

AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  AethysCache, v7.3.0.04
  AethysCore, v7.3.0.05
  AethysRotation, v7.3.0.06b
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=a2)

I've been having this pop on all my characters

**Comment by Aethys256** [comment]
Try to update to 7.3.0.06c and delete your AethysRotation.lua in WTF folder (WTF -> YourAccount -> SavedVariables), then start the game.
Will see how to prevent this in the future, ty.

**Comment by Aethys256** [comment]
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/4d895faf49bf012276e3f721744887f891ed00f6 :)
Will be available on 7.3.0.6d ;)
