### ISSUE TITLE
[Blood] Blood DK issues

### ISSUE THREAD

**Issue by drik2** [SimCMinMax/AethysRotation#64]
Could icons be greyed out icons when out of range rather than no icons at all?

'Mind Freeze' is not showing up when interruptable spell is being cast.

**Comment by chrislopez24** [comment]
added mindfreeze on https://github.com/SimCMinMax/AethysRotation/commit/24c0511cbc75b8f6173bc016a24870383c208329
and https://github.com/SimCMinMax/AethysRotation/commit/d3eb387cc07d9af2393afb135d5a6922947c5ad8
Ill add your other suggestion when i can find some free time, thanks you!

**Comment by drik2** [comment]
Thank you chris, right now the icons actually appear at full brightness even if target is out of range - so the idea would be can they appear shadowed if they are out and full bright when in range. Thank you for your time!
