### ISSUE TITLE
[Balance] Issue to predict NewMoon

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/AethysRotation#67]
The artifact spell of balance is [New Moon](http://www.wowhead.com/spell=202767/new-moon) which cycle between NewMoon > HalfMoon > FullMoon > NewMoon >...  
When you cast one you pass to the next one.  
and the spell has 3 charges, but that's 3 considered different spells (202767, 202768, 202771), and everything charges/coodown/... is stored in New moon.  
So, to determine the next spell to cast, I have a temp var that's called nextMoon where i store the next spell based on what i'm currently casting.  
See [here](https://github.com/SimCMinMax/AethysRotation/blob/master/AethysRotation_Druid/Balance.lua#L137)
AethysRotation - WoW Addon - Attempt to provide the useful and precise informations to execute the best possible DPS rotation in every situation.  

The problem is :
When the player is casting Full Moon, the next spell is New Moon, so in nextMoon I have new moon.
BUT
newMoon is the ability tha you have in the codex and it switches it's icon by itself between the spells.
So, when I am casting fullMoon, nextmoon becomes newmoon
BUT
NewMoon still has the icon of FullMoon.

What i want is to tell the player taht when he is casting full moon, his next moon will be new moon but I can't do that...
I tried finding other spells with the same icon as new moon but that doesn't work
Everything works well for the rest because i can force cast HalfMoon and Fullmoon because that's different spells that stays with their icons

**Comment by Aethys256** [comment]
You'll have to force a texture clear :) That should update it.
The cache does cache each texture, although I'll probably remove this really soon since it's probably not a performance gain (need to double check).

**Comment by Kutikuti** [comment]
I don't think it's a cache problem. The thing is, Full moon hasn't finished casting, so it's normal for the New Moon icon to still show Full Moon. Is there a way to force a specific icon on a Spell ?

**Comment by chrislopez24** [comment]
Did you try to maybe use CastAnnotate? It was added by Kojiyama iirc and allow to label an icon with text

**Comment by Kutikuti** [comment]
I could but this would not solve the issue

**Comment by Kutikuti** [comment]
Solved with https://github.com/SimCMinMax/AethysRotation/commit/ba82ef36d92bbf9d6d6962f125e60dcb1db98405
