### ISSUE TITLE
Enhancement wrong spell ID for 2 set bonus

### ISSUE THREAD

**Issue by Xaldeon** [SimCMinMax/AethysRotation#68]
Currently the config has the following spell ID as the 2 set buff "187878" while the id is "242284". This causes the addon to advise Crash Lightning on cooldown.

I've also removed S.CrashingStorm:IsAvailable() from the fillers since it was telling me to use Crash Lightning on cooldown when using this talent in a single target situation.

**Comment by lithium720** [comment]
242284 -> http://www.wowhead.com/spell=242284/lightning-crash
187878 -> http://www.wowhead.com/spell=187878/crash-lightning
187874 -> http://www.wowhead.com/spell=187874/crash-lightning

Crash lightning is generally part of all rotations because of the "Gathering Storms" buff you receive for 10 seconds for storm strike: http://www.wowhead.com/spell=198300/gathering-storms

If you still think something is wrong I will look at it closer when I have time.

**Comment by Xaldeon** [comment]
```
local function LightningCrashNotUp()
  return not Player:Buff(S.CrashLightningBuff) and AC.Tier20_2Pc
end

```
This also checks for the 2 set bonus which is the crit buff. In single target you should never use Crash Lightning unless you're going to refresh the buff.

I've edited it locally to

```
local function LightningCrashNotUp()
  return (not Player:Buff(S.CrashLightningBuff) or S.CrashLightning:TimeSinceLastCast() >= 13) and AC.Tier20_2Pc
end
```

So it doesn't tell me to spam Crash Lightning on cooldown but rather when I am missing the 2 set bonus buff or there's 3 seconds left on it. This also required me to use spell id 242284 rather than 187878.

Also removing S.CrashingStorm:IsAvailable()  from the fillers was required since it would prioritize Crash Lightning over Lava Lash.

Crash Lightning is considered a waste of Maelstrom in single target situations so it should only be used to proc your 2 set buff.

**Comment by lithium720** [comment]
That should help resolve most of the CL spam, I haven't tested it yet (didn't quite mean to close the issue, but that's ok). Otherwise as for CrashingStorm vs LavaLash prioritization I'm going to trust the SimC APL, which is what this addon is almost entirely influenced by.

**Comment by Xaldeon** [comment]
I have just done multiple 3 minute DPS runs against target dummies with both the version that includes Crashing Storm and the one without. I forgot I removed all of them since there was one thing bugging me. When you're low on Maelstrom it still suggest you to use Crashing Lightning which keeps your maelstrom low and hurts your DPS. This didn't happen every trial, but the DPS difference was noticeable when you had bad procs and started to use more Crash Lightnings at low maelstrom.

I've read up some guides and they all tell you to never use Crash Lightning in single target unless you're refreshing your 2 set bonus (Even with the Crashing Storm talent).

For now I will keep using the version without the Crashing Storm filler since it tends to hurt my DPS by a large margin when it keeps suggesting me to use Crash Lightning during low maelstrom as a filler.

I've seen rotations as Crash Lightning -> Rockbiter -> Crash Lightning -> Flametongue -> Rockbiter -> Crash Lightning being suggested where it would have been better off to just pool your maelstrom for Stormbringer procs.

**Comment by lithium720** [comment]
I tried the same thing and was unable to reproduce your results, with and without Crashing Storm talented. I ended up with worse dps by not using Crash Lightning as filler. Crash Lightning isn't called in the filler if you have less than 60 maelstrom (if we're ignoring the Alpha Wolves). Maybe I misunderstood. Maybe your case is unique. Either way my goal here is to keep the rotation in sync with the SimC APL and not any number of guides.

**Comment by Xaldeon** [comment]
`if S.CrashLightning:IsCastable("Melee", true) and ((S.CrashingStorm:IsAvailable() or Cache.EnemiesCount[8] >= 2) and Target:Debuff(S.EarthenSpikeDebuff) and Player:Maelstrom() >= 40 and OCPool60()) then
      if Player:Maelstrom() >= S.CrashLightning:Cost() then
        if AR.Cast(S.CrashLightning) then return "Cast CrashLightning" end
      end
    end`

Not sure what OCPool60 means here, but here the Maelstrom check is at 40. Which leaves you with 10 Maelstrom after a Crash Lightning. I am using the Earthen Spike talent. So I assume the bad rotations I had with Crash Lightning and low Maelstrom were during this debuff period.
