### ISSUE TITLE
[Shaman] Totem Mastery repeatedly suggested

### ISSUE THREAD

**Issue by CoilDomain** [SimCMinMax/AethysRotation#69]
It appears there's something wrong with the Totem Mastery suggestion, it'll pop up several times in a row and won't progress.

**Comment by chrislopez24** [comment]
Please, give us more info, but if i remember right that issue was fixed some days ago. Whats your addon version? Is it from Twich client or Github repo? Thanks

**Comment by chrislopez24** [comment]
Just looked into it, if you are using twitch client, the version can be out of date, there was a commit on October,22 with shaman updates, so please update from the git version instead of Twitch until we publish a new version, if the problem persists, dont hesitate to comment it here . Thanks again

**Comment by CoilDomain** [comment]
I was using the Git version, as of a few hours ago. Let me double check to make sure nothing may have been cached on my side. What kind of information do you need? It seems after a few Lava Bursts Totem Mastery is suggested once then a few times back to back.

**Comment by CoilDomain** [comment]
After some further testing, this only seems to happen when talenting Ascension, using Lighting Rod seems fine.

**Comment by lithium720** [comment]
I fixed this in 1f7c8e855944e6accecd5c2845818c274677b4cd. I have just tried to recreate this with Ascendance talented and cannot recreate it. Are you using the latest GitHub release or the branch origin?

**Comment by CoilDomain** [comment]
I am using the master branch. Looking at the change those lines are in the file I have.

**Comment by lithium720** [comment]
That should *actually* fix it for now. Thanks for the report!
