### ISSUE TITLE
[Destruction] LUA Error

### ISSUE THREAD

**Issue by Montipat** [SimCMinMax/AethysRotation#73]
Date: 2017-10-28 14:51:50
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\AethysRotation_Warlock\Destruction.lua line 332:
   attempt to call method 'BuffRemainsP' (a nil value)
Debug:
   ...erface\AddOns\AethysRotation_Warlock\Destruction.lua:332: ?()
   AethysRotation\Main.lua:332:
      AethysRotation\Main.lua:322
Locals:
(*temporary) = nil
(*temporary) = <table> {
 LastRemovedFromPlayerTime = 0
 LastAppliedOnPlayerTime = 0
 SpellType = "Player"
 LastHitTime = 0
 LastCastTime = 0
 LastDisplayTime = 0
 SpellID = 235156
}
(*temporary) = "attempt to call method 'BuffRemainsP' (a nil value)"
AC = <table> {
 RegisterForEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:46
 MAXIMUM = 40
 RegisterForSelfCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:77
 Spell = <table> {
 }
 PulseInitialized = true
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 RegisterForCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:62
 MythicDungeon = <function> defined @Interface\AddOns\AethysCore\Class\Unit\Player\MythicDungeon.lua:49
 Item = <table> {
 }
 CacheHasBeenReset = false
 LiveRealm = <function> defined @Interface\AddOns\AethysCore\Core.lua:35
 FindMacroKeyBinding = <function> defined @Interface\AddOns\AethysCore\Events\KeyBinding.lua:128
 ManuallyFilterItemRanges = <function> defined @Interface\AddOns\AethysCore\Class\Unit\Range.lua:28
 Pulse = <function> defined @Interface\AddOns\AethysCore\Main.lua:29
 BetaRealm = <function> defined @Interface\AddOns\AethysCore\Core.lua:43
 GetInstanceDifficulty = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:63
 HasTier = <function> defined @Interface\AddOns\AethysCore\Class\Unit\Player\Equipment.lua:113
 GetInstanceInfo = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:32
 Tier20_4Pc = false
 Tier19_2Pc = false
 RegisterForCombatSuffixEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:122
 MainFrame = AethysCore_MainFrame {
 }
 Equipment = <table> {
 }
 Tier19_4Pc = false
 Tier20_2Pc = false
 GetTime = <function> defined @Interface\AddOns\AethysCore\Core.lua:48
 RecoveryTimer = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:75
 OutOfCombatTime = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:90
 UnregisterForSelfCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:168
 Latency = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:69
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 CombatEnded = 1
 Print = <function> defined @Interface\AddOns\AethysCore\Core.lua:57
 CombatStarted = 0
 TTD = <table> {
 }
 Enum = <table> {
 }
 BuildVersion = <function> defined @Interface\AddOns\AethysCore\Core.lua:31
 UnregisterForCombatPrefixEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:196
 CombatTime = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:85
 RegisterForCombatPrefixEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:107
 GetEquipment = <function> defined @Interface\AddOns\AethysCore\Class\Unit\Player\Equipment.lua:24
 BMPullTime = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:95
 UnregisterForCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:154
 UnregisterForEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:137
 TTDRefresh = <function> defined @Interface\AddOns\AethysCore\Class\Unit\TimeToDie.lua:49
 RecoveryOffset = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:80
 UnregisterForPetCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:182
 RegisterForPetCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:92
 SpecID_ClassesSpecs = <table> {
 }
 GuardiansTable = <table> {
 }
 GetEnemies = <function> defined @Interface\AddOns\AethysCore\Misc\Enemies.lua:28
 GUI = <table> {
 }
 OffsetRemains = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:112
 UnregisterForCombatSuffixEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:210
 Timer = <table> {
 }
 PTRRealm = <function> defined @Interface\AddOns\AethysCore\Core.lua:39
 ImmolationTable = <table> {
 }
 GUISettings = <table> {
 }
}
range = 40
Everyone = <table> {
 Targe
AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  AethysCache, v7.3.0.06
  AethysCore, v7.3.0.06
  AethysRotation, v7.3.0.07
  AethysRotationWarlock, v
  ArcHUD3, v4.2.3
  Atlas, vv1.43.03
  AtlasBattlegrounds, vv1.43.00
  AtlasBurningCrusade, vv1.43.00
  AtlasCataclysm, vv1.43.00
  AtlasClassicWoW, vv1.43.00
  AtlasClassOrderHalls, vv1.43.00
  AtlasDungeonLocs, vv1.43.00
  AtlasLegion, vv1.43.03
  AtlasMistsofPandaria, vv1.43.00
  AtlasOutdoorRaids, vv1.43.00
  AtlasScenarios, vv1.43.00
  AtlasTransportation, vv1.43.00
  AtlasWarlordsofDraenor, vv1.43.00
  AtlasWorldEvents, vv3.23
  AtlasWrathoftheLichKing, vv1.43.00
  AtlasLoot, vv8.07.01
  AtlasLootBurningCrusade, vv8.07.01
  AtlasLootCataclysm, vv8.07.01
  AtlasLootClassic, vv8.07.01
  AtlasLootLegion, vv8.07.01
  AtlasLootMistsofPandaria, vv8.07.01
  AtlasLootWarlordsofDraenor, vv8.07.01
  AtlasLootWrathoftheLichKing, vv8.07.01
  AtlasMajorCitiesEnhanced, vv1.15
  AucAdvanced, v7.5.5724 (TasmanianThylacine)
  AucFilterBasic, v7.5.5724 (TasmanianThylacine)
  AucFilterOutlier, v7.5.5724.5459(7.5/embedded)
  AucMatchUndercut, v7.5.5724.5585(7.5/embedded)
  AucStatHistogram, v7.5.5724 (TasmanianThylacine)
  AucStatiLevel, v7.5.5724 (TasmanianThylacine)
  AucStatPurchased, v7.5.5724 (TasmanianThylacine)
  AucStatSales, v7.5.5724.5598(7.5/embedded)
  AucStatSimple, v7.5.5724 (TasmanianThylacine)
  AucStatStdDev, v7.5.5724 (TasmanianThylacine)
  AucStatWOWEcon, v7.5.5724.5613(7.5/embedded)
  AucUtilAHWindowControl, v7.5.5724.5575(7.5/embedded)
  AucUtilAppraiser, v7.5.5724.5719(7.5/embedded)
  AucUtilAskPrice, v7.5.5724.5599(7.5/embedded)
  AucUtilAutoMagic, v7.5.5724.5686(7.5/embedded)
  AucUtilCompactUI, v7.5.5724.5715(7.5/embedded)
  AucUtilEasyBuyout, v7.5.5724.5576(7.5/embedded)
  AucUtilFixAH, v7.5.5724 (TasmanianThylacine)
  AucUtilItemSuggest, v7.5.5724.5651(7.5/embedded)
  AucUtilPriceLevel, v7.5.5724.5633(7.5/embedded)
  AucUtilScanButton, v7.5.5724.5631(7.5/embedded)
  AucUtilScanFinish, v7.5.5724.5720(7.5/embedded)
  AucUtilScanProgress, v7.5.5724.4979(7.5/embedded)
  AucUtilScanStart, v7.5.5724.5347(7.5/embedded)
  AucUtilSearchUI, v7.5.5724.5721(7.5/embedded)
  AucUtilSimpleAuction, v7.5.5724.5705(7.5/embedded)
  AucUtilVendMarkup, v7.5.5724.4828(7.5/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.3.2
  Bartender4, v4.7.10
  BeanCounter, v7.5.5724 (TasmanianThylacine)
  Castbars, v
  Configator, v5.1.DEV.431(/embedded)
  DailyGlobalCheck, v
  DailyGlobalCheckLegionRareMobs, v
  DailyGlobalCheckLegionTreasureChests, v
  DailyGlobalCheckLegionWorldQuests, v
  DailyGlobalCheckWorldBosses, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.5.5724 (TasmanianThylacine)
  EnchantrixBarker, v7.5.5724 (TasmanianThylacine)
  GatherMate2, v1.41
  Informant, v7.5.5724 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.430(/embedded)
  MapCoords, v0.26
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.147
  NomiCakes, v7.3.0.1
  NPCScan, v7.3.0.6
  OmniCC, v7.3
  QuestGuru, v2.4.32
  QuestGuruSounds, v2.4.32
  SexyMap, vv7.3.0
  SlideBar, v7.5.5724 (TasmanianThylacine)
  SpellFlashCore, v2.1.5
  Stubby, v7.5.5724 (TasmanianThylacine)
  TellMeWhen, v8.4.2
  TipHelper, v5.12.DEV.405(/embedded)
  WeakAuras, v2.4.24
  BlizRuntimeLib_enUS v7.3.2.70300 <none>
  (ck=cd3)

**Comment by Kutikuti** [comment]
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/a931360ab074ce9b0c54768e161ef0aeac0122d7
Thanks for the report
