### ISSUE TITLE
Destruction Warlock Errors

### ISSUE THREAD

**Issue by Stavilde** [SimCMinMax/AethysRotation#74]
Date: 2017-10-29 11:09:07
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\AethysRotation_Warlock\Destruction.lua line 332:
   attempt to call method 'BuffRemainsP' (a nil value)
Debug:
   ...erface\AddOns\AethysRotation_Warlock\Destruction.lua:332: ?()
   AethysRotation\Main.lua:332:
      AethysRotation\Main.lua:322
Locals:
(*temporary) = nil
(*temporary) = <table> {
 LastRemovedFromPlayerTime = 0
 LastAppliedOnPlayerTime = 0
 SpellType = "Player"
 LastHitTime = 0
 LastCastTime = 0
 LastDisplayTime = 0
 SpellID = 235156
}
(*temporary) = "attempt to call method 'BuffRemainsP' (a nil value)"
AC = <table> {
 RegisterForEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:46
 MAXIMUM = 40
 RegisterForSelfCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:77
 Spell = <table> {
 }
 PulseInitialized = true
 BuildInfo = <table> {
 }
 Unit = <table> {
 }
 RegisterForCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:62
 MythicDungeon = <function> defined @Interface\AddOns\AethysCore\Class\Unit\Player\MythicDungeon.lua:49
 Item = <table> {
 }
 CacheHasBeenReset = false
 LiveRealm = <function> defined @Interface\AddOns\AethysCore\Core.lua:35
 FindMacroKeyBinding = <function> defined @Interface\AddOns\AethysCore\Events\KeyBinding.lua:128
 ManuallyFilterItemRanges = <function> defined @Interface\AddOns\AethysCore\Class\Unit\Range.lua:28
 Pulse = <function> defined @Interface\AddOns\AethysCore\Main.lua:29
 BetaRealm = <function> defined @Interface\AddOns\AethysCore\Core.lua:43
 GetInstanceDifficulty = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:63
 HasTier = <function> defined @Interface\AddOns\AethysCore\Class\Unit\Player\Equipment.lua:113
 GetInstanceInfo = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:32
 Tier20_4Pc = false
 Tier19_2Pc = false
 RegisterForCombatSuffixEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:122
 MainFrame = AethysCore_MainFrame {
 }
 Equipment = <table> {
 }
 Tier19_4Pc = false
 Tier20_2Pc = false
 GetTime = <function> defined @Interface\AddOns\AethysCore\Core.lua:48
 RecoveryTimer = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:75
 OutOfCombatTime = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:90
 UnregisterForSelfCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:168
 Latency = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:69
 LastUnitCycled = <table> {
 }
 Utils = <table> {
 }
 UnitNotInFrontTime = 0
 LastUnitCycledTime = 0
 UnitNotInFront = <table> {
 }
 CombatEnded = 1
 Print = <function> defined @Interface\AddOns\AethysCore\Core.lua:57
 CombatStarted = 0
 TTD = <table> {
 }
 Enum = <table> {
 }
 BuildVersion = <function> defined @Interface\AddOns\AethysCore\Core.lua:31
 UnregisterForCombatPrefixEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:196
 CombatTime = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:85
 RegisterForCombatPrefixEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:107
 GetEquipment = <function> defined @Interface\AddOns\AethysCore\Class\Unit\Player\Equipment.lua:24
 BMPullTime = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:95
 UnregisterForCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:154
 UnregisterForEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:137
 TTDRefresh = <function> defined @Interface\AddOns\AethysCore\Class\Unit\TimeToDie.lua:49
 RecoveryOffset = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:80
 UnregisterForPetCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:182
 RegisterForPetCombatEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:92
 SpecID_ClassesSpecs = <table> {
 }
 GuardiansTable = <table> {
 }
 GetEnemies = <function> defined @Interface\AddOns\AethysCore\Misc\Enemies.lua:28
 GUI = <table> {
 }
 OffsetRemains = <function> defined @Interface\AddOns\AethysCore\Misc\ToSort.lua:112
 UnregisterForCombatSuffixEvent = <function> defined @Interface\AddOns\AethysCore\Events\Main.lua:210
 Timer = <table> {
 }
 PTRRealm = <function> defined @Interface\AddOns\AethysCore\Core.lua:39
 ImmolationTable = <table> {
 }
 GUISettings = <table> {
 }
}
range = 40
Everyone = <table> {
 Targe
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  Ace3, v
  AethysCache, v7.3.0.06
  AethysCore, v7.3.0.06
  AethysRotation, v7.3.0.07
  AethysRotationWarlock, v
  Bartender4, v4.7.10
  DBMCore, v7.3.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  GearHelper, v1.6.6.2
  HandyNotes, vv1.4.15
  HandyNotesArgus, v0.20.0
  HandyNotesBrokenShore, vv1.21
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesHigherDimensionalLearning, v1
  HandyNotesHigherLearning, v7.1.0.0
  HandyNotesKosumoth, v1
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLegionTreasures, v1
  HandyNotesSuramarLocations, v0.0.1
  HandyNotesSuramarShalAranTelemancy, vv1.15
  HandyNotesSuramarTelemancy, v1
  HandyNotesTreasureHunter, v1
  LibAuctionScan10, vv1.0.14
  MasterPlanA, vA
  OneBag3, vr188
  OneCore, vr103
  Pawn, v2.2.15
  ServerHop, v7.3.0.1
  SpartanUI, v4.4.0
  SpartanUIArtwork, v3.3.0
  SpartanUIPartyFrames, v3.3.0
  SpartanUIPlayerFrames, v3.3.0
  SpartanUIRaidFrames, v3.3.0
  SpartanUIStyleFel, v1.0.0
  SpartanUIStyleMinimal, v3.3.0
  SpartanUIStyleTransparent, v3.3.0
  Stubby, v7.5.5724 (TasmanianThylacine)
  TomTom, vv70200-1.0.0
  WIM, v3.7.14
  BlizRuntimeLib_enUS v7.3.2.70300 <none>
  (ck=523)

**Comment by Kutikuti** [comment]
See https://github.com/SimCMinMax/AethysRotation/issues/73
