### ISSUE TITLE
Frost Mage Changes

### ISSUE THREAD

**Issue by Spedwards** [SimCMinMax/AethysRotation#75]
There are a few changes that need to be made to Frost Mage's rotation.

1. Ice Barrier. Should be up whenever possible.
2. Frost Nova. Instant cast and will triple damage from Ice Lance.
3. Spellsteal. If the target has a buff that can be stolen, steal it.
4. Invisibility/Ice Block. Good defensive spells. Not sure if they can be added, but they should be used before taking fatal damage.
5. Conjure Refreshment. I doubt this can be added, but if you don't have any Conjured Mana Buns, this should be cast to save time when you need them.
6. Blink/Shimmer. Can be used in combination with Frost Nova. If your target is within Frost Nova range, Nova then Blink/Shimmer out of damage rank.

**Comment by Kutikuti** [comment]
There could also be some more cast Prediction : 
7. Suggest glacial spike when you have 4 icicles and casting frostbolt instead of suggesting frostbolt and glacial spike when the cast is over
8. Suggest Flurry when casting ebonbolt ? Not sure of this one

**Comment by Glynnyx** [comment]
Hello,

Thanks for the feedback, we always appreciate people reaching out to offer suggestions, however I'm struggling to find a reason to implement any of the ideas. The purpose of the addon is to provide the best DPS possible and providing the user (you) with icons to display the best rotation. The note at the top of the addon states 

> WoW Addon - Attempt to provide the useful and precise informations to execute the best possible DPS rotation in every situation.

None of the suggestions contribute to the DPS what so ever, so it begs the question - what's the point? 

The spellsteal suggestion I can get behind - sure, but I would only add this if something was able to be spellstole and sephuz was equipped and up (which would lead to a DPS increase)

Unrelated to the addon its self, those type of defensive tools should be used properly and not at the first point of damage. Let's say you're progressing Mythic Kil'Jaeden, Mages are almost always used to soak a spell that requires Ice Block, but at some point in the fight you've taken 90% of your HP in damage and the addon prompts the use of Ice Block...you've essentially just wiped the raid when your time comes to soak.

**Comment by Glynnyx** [comment]
I will leave the issue open for now to implement Kuti's idea's though.

**Comment by Spedwards** [comment]
@Glynnyx 

1. Ice Barrier. Keeps you alive longer so you can deal more damage.
2. Frost Nova. Increased damage from Ice Lance.
3. Spellsteal. Steal a buff, do increased damage.
4. Invisiblity/Ice Block. Same reason as Ice Barrier. Stay alive = More Damage.
5. Conjure Refreshment. Using it beforehand saves time when you actually need it, so more time can be focused on doing damage.
6. Blink/Shimmer. Avoid enemies = less incoming damage = staying alive = more outgoing damage.

All 6 contribute to damage in some way or another.

> Unrelated to the addon its self, those type of defensive tools should be used properly and not at the first point of damage. Let's say you're progressing Mythic Kil'Jaeden, Mages are almost always used to soak a spell that requires Ice Block, but at some point in the fight you've taken 90% of your HP in damage and the addon prompts the use of Ice Block...you've essentially just wiped the raid when your time comes to soak.

That's a good argument. Perhaps there could be a toggle in the addon settings for this, or perhaps just disable this automatically if you're in a raid.

**Comment by Glynnyx** [comment]
Closed the "issue" as this is not a DPS gain to do any of these except the Spellsteal and this will be only to proc sephuz in the future... 

Another issue has been opened with Kuti's idea though.
