### ISSUE TITLE
[Havoc] Demon Hunter Rotation

### ISSUE THREAD

**Issue by Spedwards** [SimCMinMax/AethysRotation#76]
I'll try and implement this over the weekend, but since there's no Havoc rotation currently, here's one that has been working well for me.

https://www.icy-veins.com/wow/havoc-demon-hunter-pve-dps-rotation-cooldowns-abilities

Feel free to implement it before me.

**Comment by EvanMichaels** [comment]
Going to close this issue since the module was implemented a while ago. Thanks!
