### ISSUE TITLE
[Frost] Suggestions for Frost Mage

### ISSUE THREAD

**Issue by Glynnyx** [SimCMinMax/AethysRotation#77]
Thanks to Kuti for the suggestions:

1. Suggest glacial spike when you have 4 icicles and casting frostbolt instead of suggesting frostbolt and glacial spike when the cast is over
2. Suggest Flurry when casting ebonbolt ? Not sure of this one

**Comment by Kutikuti** [comment]
Added in https://github.com/SimCMinMax/AethysRotation/commit/c054ca0d76047f650930b5e1cbedaee5afdcb64c
