### ISSUE TITLE
[Rogue] Assassination Issue

### ISSUE THREAD

**Issue by erxx** [SimCMinMax/AethysRotation#78]
451x AethysRotation\Commons.lua:62: attempt to index field '?' (a nil value)
AethysRotation\Commons.lua:62: in function `Interrupt'
AethysRotation_Rogue\Assassination.lua:589: in function `?'
AethysRotation\Main.lua:296: in function <AethysRotation\Main.lua:286>

**Comment by Mystler** [comment]
Hey, can you give me a description of how to reproduce this issue?

**Comment by Aethys256** [comment]
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/ab05a02435f046659dd5a7c19fa03306b980c1af#diff-1374666c724ad1d1b92d9cadf7e379dd
