### ISSUE TITLE
[Unholy] AotD as off-gcd ability

### ISSUE THREAD

**Issue by solitha** [SimCMinMax/AethysRotation#82]
Army of the Dead should be moved off the main rotation and to a cooldown icon.

**Comment by Kutikuti** [comment]
Add an option to put AotD to off-gcd abilities

**Comment by Kutikuti** [comment]
added in https://github.com/SimCMinMax/AethysRotation/commit/3b8bf601d633711b5bdb309784d7c847e8f35f39 for the pull
