### ISSUE TITLE
Elemental: Totems repeating

### ISSUE THREAD

**Issue by solitha** [SimCMinMax/AethysRotation#85]
Just fought a mob in the Underbelly and totems kept popping up in the rotation even though they were in use.

**Comment by lithium720** [comment]
More details would be useful, like the talents you were using when it happened, the number of targets in the area, if you had AoE on, etc.

**Comment by solitha** [comment]
My apologies. AoE on, one hostile target (PvP was off, it was a rare, the Crazed Mage). Talents 3 3 1 2 2 1 1. Only legendary Eye of the Twisting Nether.

**Comment by lithium720** [comment]
I've got it setup now to where it will only ask you to cast Totem Mastery if you are missing the totem buff and haven't already casted it in the last 5 seconds. It's possible you dropped the totems in a bad spot and the game just didn't give you the buff right away / at all.
