### ISSUE TITLE
[Nameplate] AoE/DoT suggestion icon takes up 75% of the screen.

### ISSUE THREAD

**Issue by Tummieqt** [SimCMinMax/AethysRotation#90]
As per the title. What I assume is the icon that anchors to the nameplate takes up 75% of my screen in AoE/multi-target situations. Rupture on my rogue and sunfire/moonfire on my boomkin. I have determined the addon causing the issue is 'bd nameplates'. AER works just fine when it is disabled, but I have become accustomed to using bd for m+. If there is any chance of a fix that would be great.

**Comment by Aethys256** [comment]
For reference:
https://wow.curseforge.com/projects/bdnameplates

**Comment by Abotoss** [comment]
Hello, 

As per our chat on discord here are screen shots of whats happening with the debuff icons when debuffs are about to run out. All i do is dot multiple targets and when the dot is about to drop it puts a huge icon on my screen. Im using BD nameplates version 2.26 and BD core 2.11. Ive also attached a list of the addons i have installed.

<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/36359501/36071393-8fbdc5c4-0f61-11e8-812c-676ee2981807.png">


![wowscrnshot_021118_180911](https://user-images.githubusercontent.com/36359501/36071292-54f882d6-0f60-11e8-8133-1642a2d8ae45.jpg)
![wowscrnshot_021118_181026](https://user-images.githubusercontent.com/36359501/36071293-5529c508-0f60-11e8-9cf3-a5e8fc0d244c.jpg)
![wowscrnshot_021118_182646](https://user-images.githubusercontent.com/36359501/36071294-555a6f14-0f60-11e8-8d38-ab6a73e8183b.jpg)
[WTF.zip](https://github.com/SimCMinMax/AethysRotation/files/1714175/WTF.zip)

**Comment by ghr74** [comment]
Please try changing the debuff size slider in the bdnameplates options slightly, then reload UI and see if it has fixed it. Messing with the debuff slider in the bdnameplates options has been reported to have worked to fix this issue in the past.

**Comment by Abotoss** [comment]
I've tried changing the debuff sliders in BD nameplates and found no difference.

**Comment by ghr74** [comment]
This issue should be fixed in https://github.com/SimCMinMax/AethysRotation/commit/720780c6470fd413e7c23f98b511119aa3849774 . Please reopen if it persists.
