### ISSUE TITLE
[Question] How to make icon colour to black

### ISSUE THREAD

**Issue by eleni195** [SimCMinMax/AethysRotation#92]
i want to make the ui so that it doesn't show icons. i want to see only the keybinds, and black icon in background.

i don't know if you can understand me, i just only want to see black, icons, and only the keybind sortcuts in white. can you please tell me how do i do it?

what file should i alter?

**Comment by Aethys256** [comment]
The addon is an attempt to provide the useful and precise informations to execute the best possible DPS rotation in every situation. Icons are part of its key features.
It makes no sense to hide them.
