### ISSUE TITLE
[fury warrior] interrupt suggestion

### ISSUE THREAD

**Issue by Aurelkt** [SimCMinMax/AethysRotation#96]
i was arms warrior and everything was fine but since i switched to fury the addon never suggest pummel to interrupt . (interrupt and pummel as off gcd checked) i tried to change nameplate from elvui to wow ui but no improvement.

**Comment by Kutikuti** [comment]
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/6cde97d6a0741629bbc3c867048eb6dcb5ce2364
