### ISSUE TITLE
[Frost] Death Knight - APL - Frost Strike ahead of Rime Proc > 90 RP

### ISSUE THREAD

**Issue by SysNaabu** [SimCMinMax/AethysRotation#97]
Version : 7.3.2.01

When playing a Frost DK, AethysRotation will suggest using Frost Strike over Howling Blast when there is a Rime Proc at greater than 90 RP despite Rime Proc being higher in the priority. 

(This should be the case for the Obliteration window, but appears to follow the same outside during normal conditions where the priority is shifted and Rime is #2 in the Priority list)

**Comment by chrislopez24** [comment]
Hi, first of all thanks for taking the time to report issues, i appreciate it.

I've been looking at the frost APL and Frost strike is higher on priority than hb, according to:
```
actions.standard+=/frost_strike,if=(!talent.shattering_strikes.enabled|debuff.razorice.stack<5)&runic_power.deficit<10 
actions.standard+=/howling_blast,if=buff.rime.up`
```
even with obliteration
```

actions.obliteration+=/howling_blast,if=buff.rime.up&spell_targets.howling_blast>1
actions.obliteration+=/howling_blast,if=!buff.rime.up&spell_targets.howling_blast>2&rune>3&talent.freezing_fog.enabled&talent.gathering_storm.enabled
actions.obliteration+=/frost_strike,if=!buff.rime.up|rune.time_to_1>=gcd|runic_power.deficit<20
actions.obliteration+=/howling_blast,if=buff.rime.up
```

it seems like prioritizing fs over a rime proc in certain situation is a dps gain. Anyway, if you think something can be tweaked on the APL you can always contact me (Krich) or Melekus. Thanks you!

**Comment by SysNaabu** [comment]
Ah looking at that APL line I think is where I left out some info

>actions.standard+=/frost_strike,if=(!talent.shattering_strikes.enabled|debuff.razorice.stack<5)&runic_power.deficit<10 

This is without currently taking Shattering Strikes as I believe that is only the case when you have the T21 4pc according to Melekus' guide. Currently in testing, I am still using Runic Attentuation.
