### ISSUE TITLE
[Arcane Mage]

### ISSUE THREAD

**Issue by solitha** [SimCMinMax/AethysRotation#98]
186x AethysRotation_Mage\Arcane.lua:289: attempt to index field 'MantleofTheFirstKirinTor' (a nil value)
AethysRotation_Mage\Arcane.lua:289: in function <AethysRotation_Mage\Arcane.lua:218>
AethysRotation_Mage\Arcane.lua:437: in function `?'
AethysRotation\Main.lua:440: in function <AethysRotation\Main.lua:422>

Locals:
InCombatSkipped

________________________________________
367x AethysRotation_Mage\Arcane.lua:348: attempt to compare number with boolean
AethysRotation_Mage\Arcane.lua:348: in function <AethysRotation_Mage\Arcane.lua:318>
AethysRotation_Mage\Arcane.lua:441: in function `?'
AethysRotation\Main.lua:431: in function <AethysRotation\Main.lua:409>

Locals:
InCombatSkipped

**Comment by Kutikuti** [comment]
Should be fixed with https://github.com/SimCMinMax/AethysRotation/commit/b8a62c3bfb7a1a5cdbe160a57142255b30786d8b
